# Header
menu:
  Home: /
  Archives: /archives
  About Me: /About me.html
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
# - tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'yearly'
show_count: true

# Miscellaneous
google_analytics: UA-115451279-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# MathJax Support
mathjax: true